// <auto-generated />
using System;
using FreeBudget.Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FreeBudget.Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260512193644_RenameUserToMember")]
    partial class RenameUserToMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FreeBudget.Ledger.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("OwedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("owed_by_member_id");

                    b.Property<Guid>("PaidByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_member_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PaidByMemberId");

                    b.HasIndex("TransactionId")
                        .HasFilter("transaction_id IS NOT NULL");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("FreeBudget.Ledger.Domain.Entities.LedgerEntry", b =>
                {
                    b.OwnsOne("FreeBudget.SharedKernel.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency_code");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("ledger_entries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
